### ISSUE TITLE
RuntimeError: d.is_cuda() INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by huangxin168** [MRzzm/DINet#25]
My training got this error when using ONE 4090 gpu:

train_DINet_frame64 ===> Epoch[90](198/3913):  Loss_DI: 0.2199 Loss_GI: 0.3163 Loss_perception: 2.4996 Loss_g: 2.8160 lr_g = 0.0001000 
Traceback (most recent call last):
  File "train_DINet_frame.py", line 121, in <module>
    loss_g.backward()
  File "/root/miniconda3/envs/dinet/lib/python3.7/site-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/root/miniconda3/envs/dinet/lib/python3.7/site-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: d.is_cuda() INTERNAL ASSERT FAILED at "../c10/cuda/impl/CUDAGuardImpl.h":30, please report a bug to PyTorch. 

this error also randomly occurs on forward.

It seams related to nn.DataParallel while I use single GPU.
Any idea on this will be most appreciative.

**Comment by huangxin168** [comment]
Sorry!
Finally found that it's my dataset's problem, some frame does not have face, and made this errors.

**Comment by kunqueen** [comment]
> Sorry! Finally found that it's my dataset's problem, some frame does not have face, and made this errors.

@huangxin168 Hi, I meet the same error in my task. The error randomly occurs and I don't know how to sovle. I would like to ask how you deal with this problem.

**Comment by dunyang97** [comment]
@kunqueen hi, do you sovle it? i'm also face to the same issue, and have test sevaral diffient cobination version of systen_cuda, conda_env_torch_cuda, python and ubuntu system,  the problem still occur. But the same code could successfully run at other device, without this error
