### ISSUE TITLE
用自己的视频数据测试，推理时视频帧数与openface 生成的csv的帧数不一致

### ISSUE THREAD

**Issue by muximuxi** [MRzzm/DINet#27]
您好！
用自己的视频数据测试，推理时视频帧数与openface 生成的csv的帧数不一致，请问怎么解决？是视频源有问题吗？但是换了好几个视频都是这样：
The video_landmark_data.shape:  249
aligning frames with driving audio
len_video_frames:  250
Traceback (most recent call last):
  File "inference.py", line 67, in <module>
    raise ('video frames are misaligned with detected landmarks')
TypeError: exceptions must derive from BaseException

**Comment by SetoDon** [comment]
I also have the same problem, how to solve it.

**Comment by Laixinsz** [comment]
抛弃多余的帧数，截取openface检测的帧数，可以继续生成，但是不知道会不会影响效果，用dinet自带的示例视频用openface生成csv文件不会出现这种帧数不一致的情况，不知道设么原因，自带的示例视频是29fps/s的

**Comment by ZYBOBO** [comment]
可以把帧率调成25fps/s的试试

**Comment by ZYBOBO** [comment]
> 抛弃多余的帧数，截取openface检测的帧数，可以继续生成，但是不知道会不会影响效果，用dinet自带的示例视频用openface生成csv文件不会出现这种帧数不一致的情况，不知道设么原因，自带的示例视频是29fps/s的

可以把帧率调成25fps/s的试试

**Comment by ZYBOBO** [comment]
> 抛弃多余的帧数，截取openface检测的帧数，可以继续生成，但是不知道会不会影响效果，用dinet自带的示例视频用openface生成csv文件不会出现这种帧数不一致的情况，不知道设么原因，自带的示例视频是29fps/s的

请教一下，利用OpenFace得到.csv文件的完整命令是啥？谢谢~

**Comment by Laixinsz** [comment]
docker exec -it openface /home/openface-build/build/bin/FeatureExtraction -f /tmp/openface/fc7496f57248684429995b45ecfebd0f.mp4 -2Dfp -wild -tracked -nomask  -out_dir /tmp/openface/fc7496f57248684429995b45ecfebd0fcsv
我用docker安装的。不过经常会报
0% 10% BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
BLAS : Program is Terminated. Because you tried to allocate too many memory regions.
但是csv是生成了，可能没有完整生成，生成了部分帧。
> > 抛弃多余的帧数，截取openface检测的帧数，可以继续生成，但是不知道会不会影响效果，用dinet自带的示例视频用openface生成csv文件不会出现这种帧数不一致的情况，不知道设么原因，自带的示例视频是29fps/s的
> 
> 请教一下，利用OpenFace得到.csv文件的完整命令是啥？谢谢~

**Comment by laishujie** [comment]
> 您好！ 用自己的视频数据测试，推理时视频帧数与openface 生成的csv的帧数不一致，请问怎么解决？是视频源有问题吗？但是换了好几个视频都是这样： The video_landmark_data.shape: 249 aligning frames with driving audio len_video_frames: 250 Traceback (most recent call last): File "inference.py", line 67, in raise ('video frames are misaligned with detected landmarks') TypeError: exceptions must derive from BaseException

如果你是使用应用程序的话，尝试换一下检测器试一试。
![Snipaste_2023-11-17_16-45-16](https://github.com/MRzzm/DINet/assets/16934884/63ff0584-fcc1-4001-bdd4-d4f1c29ae917)

**Comment by zxc67373** [comment]
有可能是因为没有检测到人脸，所以漏了

**Comment by Inferencer** [comment]
确保视频尺寸为 1920x1080
