### ISSUE TITLE
运行执行代码教程出现问题Traceback (most recent call last):   File "inference.py", line 88, in <module>     raise ('our method can not handle videos with large change of facial size!!')

### ISSUE THREAD

**Issue by lmpeng12** [MRzzm/DINet#36]
运行代码
python inference.py --mouth_region_size=256 --source_video_path=./asserts/examples/test4.mp4 --source_openface_landmark_path=./asserts/examples/test4.csv --driving_audio_path=./asserts/examples/driving_audio_4.wav --pretrained_clip_DINet_path=./asserts/clip_training_DINet_256mouth.pth  
出现这个问题。
Traceback (most recent call last):
  File "inference.py", line 88, in <module>
    raise ('our method can not handle videos with large change of facial size!!')

运行代码
python inference.py --mouth_region_size=256 --source_video_path=./asserts/examples/test24.mp4 --source_openface_landmark_path=./asserts/examples/test24.csv --driving_audio_path=./asserts/examples/driving_audio_2.wav --pretrained_clip_DINet_path=./asserts/clip_training_DINet_256mouth.pth  
出现
loading facial landmarks from : ./asserts/examples/test24.csv
aligning frames with driving audio
Traceback (most recent call last):
  File "inference.py", line 59, in <module>
    raise ('video frames are misaligned with detected landmarks')
TypeError: exceptions must derive from BaseException

如何解决？

**Comment by Inferencer** [comment]
I havent seen that issue myself but it might be fixed here
https://github.com/MRzzm/DINet/issues/9

**Comment by lmpeng12** [comment]
> I havent seen that issue myself but it might be fixed here #9

thank you，but it seems that it still cannot solve this problem

**Comment by Inferencer** [comment]
> > I havent seen that issue myself but it might be fixed here #9
> 
> thank you，but it seems that it still cannot solve this problem

It could be the fact that the example videos are all 29 fps and they where tracked at 29fps but when it comes to inference the code converts the video to 25fps (badly), try convert the video to 25
[Joe.zip](https://github.com/MRzzm/DINet/files/11837797/Joe.zip)
fps in a video editing software and re-track for the csv yourself

or if my compressed filed uploads then extract and use those as a test as that is what i did to the file

**Comment by Inferencer** [comment]
also i just got this again as i selected 3d landmark settings instead of 2d ones in openface

**Comment by gorgeousdays** [comment]
if you don't have any solution, you can forcely let  function `compute_crop_radius` return `True,radius_max`, it works

**Comment by Inferencer** [comment]
> if you don't have any solution, you can forcely let function `compute_crop_radius` return `True,radius_max`, it works

nice, would there be any benefit of using this other than to solve the error?

**Comment by gorgeousdays** [comment]
In fact, the problem arises because the predicted face range exceeds the image range, which prevents us from effectively cropping the image.However, this problem is like  `crOP_ radius=5` and `frame_ data=[1,2,3,4]`, of course the  radius exceeds the scope of frame_data, then it report an  error. But we can let it return `True` just like still use the frame_ Data [2:5] gets [3,4] without reporting an error.

**Comment by gorgeousdays** [comment]
> > if you don't have any solution, you can forcely let function `compute_crop_radius` return `True,radius_max`, it works
> 
> nice, would there be any benefit of using this other than to solve the error?

In fact, the problem arises because the predicted face range exceeds the image range, which prevents us from effectively cropping the image.However, this problem is like  `crop_ radius=5` and `frame_ data=[1,2,3,4]`, of course the  radius exceeds the scope of frame_data, then it report an  error. But we can let it return `True` just like still use the `frame_ data [2:crop_radius]` gets [3,4] without reporting an error.

**Comment by Simon-BIA** [comment]
Is there any solution to this, I tried commenting out line 88 and 89 but it didn't work.
