### ISSUE TITLE
How to fix this error HELP!

### ISSUE THREAD

**Issue by Loopformdisc** [MRzzm/DINet#50]
extracting: input/888.zip           
Traceback (most recent call last):
  File "inference.py", line 33, in <module>
    raise ('wrong video path : {}'.format(opt.source_video_path))
TypeError: exceptions must derive from BaseException

**Comment by ngbien83** [comment]
888.zip is not a video file

**Comment by Loopformdisc** [comment]
Still the same problem 

Downloading...
From: https://drive.google.com/uc?id=1XGU1ZaozShHOTr06LzkIlxkWJYN3xlnm
To: /content/DINet/input.zip
100% 12.1M/12.1M [00:00<00:00, 49.0MB/s]
Archive:  input.zip
  inflating: input/888.avi           
  inflating: input/888.txt           
  inflating: input/888.wav           
Traceback (most recent call last):
  File "inference.py", line 33, in <module>
    raise ('wrong video path : {}'.format(opt.source_video_path))
TypeError: exceptions must derive from BaseException

**Comment by Inferencer** [comment]
your vid needs to be mp4 not avi i think your using the video that openface outputs

**Comment by Elsaam2y** [comment]
The format of your video seems to be incorrect
