### ISSUE TITLE
batch_size from 24 to 12, same Runtime error.

### ISSUE THREAD

**Issue by Daniel-ccx** [MRzzm/DINet#57]
_**python train_DINet_frame.py --augment_num=32 --mouth_region_size=64 --batch_size=12 --result_path=./asserts/training_model_weight/frame_training_64**_

===> Epoch[140](0/5):  Loss_DI: 0.2479 Loss_GI: 0.2368 Loss_perception: 3.3630 lr_g = 0.0001000
===> Epoch[140](1/5):  Loss_DI: 0.2540 Loss_GI: 0.2488 Loss_perception: 3.3271 lr_g = 0.0001000
===> Epoch[140](2/5):  Loss_DI: 0.2495 Loss_GI: 0.2713 Loss_perception: 3.3558 lr_g = 0.0001000
===> Epoch[140](3/5):  Loss_DI: 0.2564 Loss_GI: 0.2490 Loss_perception: 3.2059 lr_g = 0.0001000
===> Epoch[140](4/5):  Loss_DI: 0.2554 Loss_GI: 0.2251 Loss_perception: 3.2064 lr_g = 0.0001000
learning rate = 0.0001000
learning rate = 0.0001000
./asserts/training_model_weight/frame_training_64/netG_model_epoch_140.pth ====================================================================================================
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 441, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 668, in _save
    zip_file.write_record(name, storage.data_ptr(), num_bytes)
RuntimeError: [enforce fail at inline_container.cc:471] . PytorchStreamWriter failed writing file data/77: file write failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_DINet_frame.py", line 121, in <module>
    torch.save(states, model_out_path)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 442, in save
    return
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 291, in __exit__
    self.file_like.write_end_of_file()
RuntimeError: [enforce fail at inline_container.cc:337] . unexpected pos 202576832 vs 202576720

**Comment by Daniel-ccx** [comment]
pytorch 2.0.1,
cu117
python3.8

**Comment by Daniel-ccx** [comment]
磁盘没空间了
