### ISSUE TITLE
  File "inference.py", line 59, in <module>     raise ('video frames are misaligned with detected l

### ISSUE THREAD

**Issue by itzsalle** [MRzzm/DINet#76]
please help me!!!!! its the right video.
i choosed the same video as csv!!!!!
ive tried like a thousand times!!!!

loading facial landmarks from : ./asserts/examples/jimmieåk4.csv
aligning frames with driving audio
Traceback (most recent call last):
  File "inference.py", line 59, in <module>
    raise ('video frames are misaligned with detected landmarks')

**Comment by Inferencer** [comment]
> please help me!!!!! its the right video. i choosed the same video as csv!!!!! ive tried like a thousand times!!!!
> 
> loading facial landmarks from : ./asserts/examples/jimmieåk4.csv aligning frames with driving audio Traceback (most recent call last): File "inference.py", line 59, in raise ('video frames are misaligned with detected landmarks')

it could be a number of things

1. openface outputs a .avi file so make sure in your inference your using jimmieåk4.mp4 not the video the openface outputs
2. ensure the video is 25fps when before using openface (probs not the cause of the issue)
3. ensure the correct options are selected in openface as on the repo it says 2D landmark & tracked videos but is formatted in a way that makes it look like only one option but its 2 options
4. test on the assets files and see if the issue occurs with them

**Comment by NickVitali** [comment]
I have the same problem. The example files work, but with the file I made using Openface it doesn't. 
Here's the file I use...

[trial1.csv](https://github.com/MRzzm/DINet/files/13658595/trial1.csv)

https://github.com/MRzzm/DINet/assets/153491519/4435ed30-f4b5-48a8-80db-ff549ae74e8b

**Comment by Inferencer** [comment]
> I have the same problem. The example files work, but with the file I made using Openface it doesn't. Here's the file I use...
> 
> [trial1.csv](https://github.com/MRzzm/DINet/files/13658595/trial1.csv)
> trial1.mp4

I downloaded your vid, turns out the size was wrong you should have used 1920x1080 but you used 912x512, I put the video in davinci and made sure it was exported to the correct size and re-did the csv & it works now
https://streamable.com/vvn3z8
