### ISSUE TITLE
Error while frame training

### ISSUE THREAD

**Issue by ashu-jb** [MRzzm/DINet#91]
I've been getting this error while doing custom training on my own dataset. 

**Input command**: python train_DINet_frame.py --augment_num=32 --mouth_region_size=64 --batch_size=24 --result_path=./asserts/training_model_weight/frame_training_64

**Output**:

```
start loading data
finish loading
/home/azure/anaconda3/envs/dinet/lib/python3.7/site-packages/torch/nn/functional.py:3385: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.

  warnings.warn("Default grid_sample and affine_grid behavior has changed "

/home/azure/anaconda3/envs/dinet/lib/python3.7/site-packages/torch/nn/functional.py:3063: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.

  "See the documentation of nn.Upsample for details.".format(mode))

/home/azure/anaconda3/envs/dinet/lib/python3.7/site-packages/torch/nn/functional.py:3103: UserWarning: The default behavior for interpolate/upsample with float scale_factor changed in 1.6.0 to align with other frameworks/libraries, and now uses scale_factor directly, instead of relying on the computed output size. If you wish to restore the old behavior, please set recompute_scale_factor=True. See the documentation of nn.Upsample for details. 

  warnings.warn("The default behavior for interpolate/upsample with float scale_factor changed "

===> Epoch[1](0/12):  Loss_DI: 0.5604 Loss_GI: 0.8967 Loss_perception: 20.2495 lr_g = 0.0001000 
===> Epoch[1](1/12):  Loss_DI: 0.4402 Loss_GI: 0.6007 Loss_perception: 18.8938 lr_g = 0.0001000 
===> Epoch[1](2/12):  Loss_DI: 0.3320 Loss_GI: 0.2409 Loss_perception: 18.1436 lr_g = 0.0001000 
===> Epoch[1](3/12):  Loss_DI: 0.2856 Loss_GI: 0.0559 Loss_perception: 17.0328 lr_g = 0.0001000 
===> Epoch[1](4/12):  Loss_DI: 0.3609 Loss_GI: 0.0941 Loss_perception: 15.9176 lr_g = 0.0001000 
===> Epoch[1](5/12):  Loss_DI: 0.3335 Loss_GI: 0.2115 Loss_perception: 14.7737 lr_g = 0.0001000 
===> Epoch[1](6/12):  Loss_DI: 0.2931 Loss_GI: 0.3687 Loss_perception: 13.8251 lr_g = 0.0001000 
===> Epoch[1](7/12):  Loss_DI: 0.2961 Loss_GI: 0.4861 Loss_perception: 13.0843 lr_g = 0.0001000 
===> Epoch[1](8/12):  Loss_DI: 0.3162 Loss_GI: 0.5163 Loss_perception: 12.4631 lr_g = 0.0001000 
===> Epoch[1](9/12):  Loss_DI: 0.3200 Loss_GI: 0.4733 Loss_perception: 11.8717 lr_g = 0.0001000 
===> Epoch[1](10/12):  Loss_DI: 0.3100 Loss_GI: 0.3844 Loss_perception: 11.3092 lr_g = 0.0001000 
===> Epoch[1](11/12):  Loss_DI: 0.2942 Loss_GI: 0.2811 Loss_perception: 11.1683 lr_g = 0.0001000 

learning rate = 0.0001000
learning rate = 0.0001000

===> Epoch[2](0/12):  Loss_DI: 0.2865 Loss_GI: 0.1957 Loss_perception: 10.8955 lr_g = 0.0001000 
===> Epoch[2](1/12):  Loss_DI: 0.2894 Loss_GI: 0.1566 Loss_perception: 10.2868 lr_g = 0.0001000 
===> Epoch[2](2/12):  Loss_DI: 0.2956 Loss_GI: 0.1650 Loss_perception: 10.4405 lr_g = 0.0001000 
===> Epoch[2](3/12):  Loss_DI: 0.2897 Loss_GI: 0.2117 Loss_perception: 10.0963 lr_g = 0.0001000 
===> Epoch[2](4/12):  Loss_DI: 0.2800 Loss_GI: 0.2782 Loss_perception: 9.7757 lr_g = 0.0001000 
===> Epoch[2](5/12):  Loss_DI: 0.2782 Loss_GI: 0.3388 Loss_perception: 9.6991 lr_g = 0.0001000 
===> Epoch[2](6/12):  Loss_DI: 0.2823 Loss_GI: 0.3705 Loss_perception: 9.4301 lr_g = 0.0001000 
===> Epoch[2](7/12):  Loss_DI: 0.2892 Loss_GI: 0.3583 Loss_perception: 9.0951 lr_g = 0.0001000 
===> Epoch[2](8/12):  Loss_DI: 0.2907 Loss_GI: 0.3138 Loss_perception: 8.8685 lr_g = 0.0001000 
===> Epoch[2](9/12):  Loss_DI: 0.2910 Loss_GI: 0.2529 Loss_perception: 8.8726 lr_g = 0.0001000 
===> Epoch[2](10/12):  Loss_DI: 0.2900 Loss_GI: 0.2090 Loss_perception: 8.5388 lr_g = 0.0001000 
===> Epoch[2](11/12):  Loss_DI: 0.2907 Loss_GI: 0.1944 Loss_perception: 8.5192 lr_g = 0.0001000 

learning rate = 0.0001000
learning rate = 0.0001000
Checkpoint saved to 2

===> Epoch[3](0/12):  Loss_DI: 0.2939 Loss_GI: 0.2088 Loss_perception: 8.4030 lr_g = 0.0001000 
===> Epoch[3](1/12):  Loss_DI: 0.2963 Loss_GI: 0.2414 Loss_perception: 8.1049 lr_g = 0.0001000 
===> Epoch[3](2/12):  Loss_DI: 0.2964 Loss_GI: 0.2812 Loss_perception: 8.2433 lr_g = 0.0001000 
===> Epoch[3](3/12):  Loss_DI: 0.2977 Loss_GI: 0.3023 Loss_perception: 7.8428 lr_g = 0.0001000 
===> Epoch[3](4/12):  Loss_DI: 0.2983 Loss_GI: 0.2951 Loss_perception: 7.8498 lr_g = 0.0001000 
===> Epoch[3](5/12):  Loss_DI: 0.2917 Loss_GI: 0.2659 Loss_perception: 7.6060 lr_g = 0.0001000 
===> Epoch[3](6/12):  Loss_DI: 0.2871 Loss_GI: 0.2269 Loss_perception: 7.6223 lr_g = 0.0001000 
===> Epoch[3](7/12):  Loss_DI: 0.2830 Loss_GI: 0.2065 Loss_perception: 7.4132 lr_g = 0.0001000 
===> Epoch[3](8/12):  Loss_DI: 0.2790 Loss_GI: 0.2145 Loss_perception: 7.3768 lr_g = 0.0001000 
===> Epoch[3](9/12):  Loss_DI: 0.2740 Loss_GI: 0.2442 Loss_perception: 7.5608 lr_g = 0.0001000 
===> Epoch[3](10/12):  Loss_DI: 0.2666 Loss_GI: 0.2801 Loss_perception: 7.1374 lr_g = 0.0001000 
===> Epoch[3](11/12):  Loss_DI: 0.2602 Loss_GI: 0.3003 Loss_perception: 6.9730 lr_g = 0.0001000 

learning rate = 0.0001000
learning rate = 0.0001000

===> Epoch[4](0/12):  Loss_DI: 0.2563 Loss_GI: 0.2893 Loss_perception: 7.0541 lr_g = 0.0001000 

Traceback (most recent call last):

  File "train_DINet_frame.py", line 60, in <module>
    for iteration, data in enumerate(training_data_loader):
  File "/home/azure/anaconda3/envs/dinet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/azure/anaconda3/envs/dinet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/azure/anaconda3/envs/dinet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/azure/anaconda3/envs/dinet/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 83, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/azure/anaconda3/envs/dinet/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 83, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/azure/anaconda3/envs/dinet/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [29, 5] at entry 0 and [29, 4] at entry 2
```

Please suggest ways to debug the problem

**Comment by Tingtingzhanga** [comment]
你好，我也遇到了同样的问题，请问你找到解决方法了吗

**Comment by tailangjun** [comment]
我的类似
start train_frame(64x64)
start loading data
finish loading
Traceback (most recent call last):
  File "train_DINet_frame.py", line 60, in <module>
    for iteration, data in enumerate(training_data_loader):
  File "/home/tailangjun/.conda/envs/dinet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/tailangjun/.conda/envs/dinet/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/tailangjun/.conda/envs/dinet/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/tailangjun/.conda/envs/dinet/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 83, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/tailangjun/.conda/envs/dinet/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 83, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/tailangjun/.conda/envs/dinet/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [15, 104, 80] at entry 0 and [6, 104, 80] at entry 4

**Comment by tailangjun** [comment]
我查了一下，感觉问题出在 dataset_DINet_frame.py的 def __getitem__(self, index):

```python
random_anchor = random.sample(range(video_clip_num), 6)
```

如果 video_clip_num不足 6个会导致，ValueError: Sample larger than population or is negative
如果改用 `random_anchor = random.sample(range(video_clip_num), min(6, video_clip_num))`就会出现 RuntimeError: stack expects each tensor to be equal size

为了验证是这个地方的问题，我将代码改成下面这样，就不再报错了

```python
if video_clip_num < 6:
    random_anchor = random.sample(range(video_clip_num), video_clip_num)
    # 前面补充0个0，后面补充 6-video_clip_num个 0
    random_anchor = np.pad(random_anchor, (0, 6-video_clip_num), 'constant', constant_values=(0, -1))
else:
    random_anchor = random.sample(range(video_clip_num), 6)
```

但这样改不太合适，我觉得根本原因还是视频的时长太短，video_clip_num不足 6，也就是帧数不足6x9+1=55帧，所以最简单的方式是做数据集时过滤掉那些 帧数不足55帧的视频

**Comment by yunyu** [comment]
I filtered out all samples where video_clip_num < 6 in the JSON dataset creation, and am still running into the OP's error (which is different from @tailangjun's). Investigating

**Comment by tailangjun** [comment]
> I filtered out all samples where video_clip_num < 6 in the JSON dataset creation, and am still running into the OP's error (which is different from @tailangjun's). Investigating

帧数阈值之前写错了，这次更新了，得大于等于55帧。其实大于等于54帧就可以了的，但是作者的计算有点问题
```python
end_frame_index = list(range(opt.clip_length, frame_length, opt.clip_length))
```
这里用的是 range(start, stop, step)，计数到 stop 结束，但不包括 stop，说明最后一帧 frame_length是没有用上的，应该改成 frame_length + 1

**Comment by LiaoYujia** [comment]
> > I filtered out all samples where video_clip_num < 6 in the JSON dataset creation, and am still running into the OP's error (which is different from @tailangjun's). Investigating
> 
> 帧数阈值之前写错了，这次更新了，得大于等于55帧。其实大于等于54帧就可以了的，但是作者的计算有点问题
> 
> ```python
> end_frame_index = list(range(opt.clip_length, frame_length, opt.clip_length))
> ```
> 
> 这里用的是 range(start, stop, step)，计数到 stop 结束，但不包括 stop，说明最后一帧 frame_length是没有用上的，应该改成 frame_length + 1

你好，想咨询下这详细是怎么改的呢？没看明白。
是在 DINet-master\data_processing.py 下

end_frame_index = list(range(clip_length, frame_length, clip_length))

修改成这样吗？
end_frame_index = list(range(clip_length, frame_length + 1 , clip_length))

**Comment by tailangjun** [comment]
> > > I filtered out all samples where video_clip_num < 6 in the JSON dataset creation, and am still running into the OP's error (which is different from @tailangjun's). Investigating
> > 
> > 
> > 帧数阈值之前写错了，这次更新了，得大于等于55帧。其实大于等于54帧就可以了的，但是作者的计算有点问题
> > ```python
> > end_frame_index = list(range(opt.clip_length, frame_length, opt.clip_length))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这里用的是 range(start, stop, step)，计数到 stop 结束，但不包括 stop，说明最后一帧 frame_length是没有用上的，应该改成 frame_length + 1
> 
> 你好，想咨询下这详细是怎么改的呢？没看明白。 是在 DINet-master\data_processing.py 下
> 
> end_frame_index = list(range(clip_length, frame_length, clip_length))
> 
> 修改成这样吗？ end_frame_index = list(range(clip_length, frame_length + 1 , clip_length))

是的，这样子改就可以了
