### ISSUE TITLE
 File "data_processing.py", line 90, in crop_face_according_openfaceLM     raise ('run last step to extract video frame')

### ISSUE THREAD

**Issue by obtuseanglor** [MRzzm/DINet#96]
(pytorch) wsy@liu-P7920:~/model/DINet-master$ python data_processing.py --crop_face
“cropping face from video: RD_Radio22_25fps ...
Traceback (most recent call last):
  File "data_processing.py", line 180, in <module>
    crop_face_according_openfaceLM(opt.openface_landmark_dir,opt.video_frame_dir,opt.crop_face_dir,opt.clip_length)
  File "data_processing.py", line 90, in crop_face_according_openfaceLM
    raise ('run last step to extract video frame')
TypeError: exceptions must derive from BaseException”
为什么会出现这种情况？？

**Comment by hatakeyama-poke** [comment]
Did you run the command "python data_processing.py --extract_video_frame"?
